### ISSUE TITLE
Blurry Image on Welcome Page

### ISSUE THREAD

**Issue by MoutasimQazi** [Bot-Rakshit/bm_frontend#42]
### Description
On the welcome page of the website/application, the current image appears blurry. This affects the visual appeal and quality of the page, potentially impacting user experience negatively.

### Steps to Reproduce
1. Navigate to the welcome page of the application.
2. Observe the image section.
3. Notice that the image is blurry or low resolution.

### Expected Behavior
The image on the welcome page should be clear and of high resolution, providing a visually appealing introduction to the application.

### Proposed Solution
Instead of the current blurry image, consider adding a new element that includes a selection of high-quality random images. This will enhance the visual appeal of the welcome page and provide a better first impression to users.

### Screenshot
![Screenshot 2024-07-18 022131](https://github.com/user-attachments/assets/6fc2b55a-c275-4202-87ab-17d78e0e3319)

**Comment by MoutasimQazi** [comment]
@Bot-Rakshit Thanks but anyone that want work on this they could work it was just an suggestion

**Comment by SarveshK16** [comment]
@Bot-Rakshit  I am working on this issue, any suggestion from where can I unblur this image or from where can I generate a new one with a prompt?

**Comment by SarveshK16** [comment]
Below are the before and after images - 
Before: 
<img width="960" alt="image" src="https://github.com/user-attachments/assets/42bf52d3-355a-4d49-b728-e2633a05315a">

After: 
<img width="960" alt="image" src="https://github.com/user-attachments/assets/f9ba6f45-2124-4579-91cb-e3b3186bf699">

PS- I have also fixed the chess.username issue. As you can see in before snap, whole username is not visible, which is fixed in the after snap. 

Let me know if this is okay, or need to enhance the image?

**Comment by Prathamesh-B** [comment]
Good work! Later on, we might redesign the welcome page, so no worries—you can open a PR now.

**Comment by SarveshK16** [comment]
Thanks @Prathamesh-B ! PR created - #109
